22/01/21 (19:03:19) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:03:19) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:03:52) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:03:52) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:07:17) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:07:17) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:08:22) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:08:22) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:11:27) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:11:27) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:12:56) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:12:56) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:14:17) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:14:17) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:16:19) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:16:19) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
22/01/21 (19:16:35) | ERROR: Exception while getting cpu frequency!
22/01/21 (19:16:35) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/bpytop.py", line 2935, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.59/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/01/21 (18:15:30) | ERROR: Exception while getting cpu frequency!
23/01/21 (18:15:30) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/01/21 (20:45:21) | ERROR: Exception while getting cpu frequency!
23/01/21 (20:45:21) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/01/21 (20:45:29) | ERROR: Exception while getting cpu frequency!
23/01/21 (20:45:29) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/01/21 (20:47:14) | ERROR: Exception while getting cpu frequency!
23/01/21 (20:47:14) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
24/01/21 (16:07:40) | ERROR: Exception while getting cpu frequency!
24/01/21 (16:07:40) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:57:00) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:57:00) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:57:59) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:57:59) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:58:07) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:58:07) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:58:39) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:58:39) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:59:18) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:59:18) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (12:59:25) | ERROR: Exception while getting cpu frequency!
25/01/21 (12:59:25) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
25/01/21 (13:00:24) | ERROR: Exception while getting cpu frequency!
25/01/21 (13:00:24) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
26/01/21 (13:04:47) | ERROR: Exception while getting cpu frequency!
26/01/21 (13:04:47) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/bpytop.py", line 3000, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.60/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
27/01/21 (21:24:35) | ERROR: Exception while getting cpu frequency!
27/01/21 (21:24:35) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
31/01/21 (17:06:09) | ERROR: Exception while getting cpu frequency!
31/01/21 (17:06:09) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
01/02/21 (23:37:20) | ERROR: Exception while getting cpu frequency!
01/02/21 (23:37:20) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/02/21 (11:23:40) | ERROR: Exception while getting cpu frequency!
05/02/21 (11:23:40) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
10/02/21 (14:41:00) | ERROR: Exception while getting cpu frequency!
10/02/21 (14:41:00) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
13/02/21 (11:30:06) | ERROR: Exception while getting cpu frequency!
13/02/21 (11:30:06) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/bpytop.py", line 3030, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.61/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
15/02/21 (17:56:21) | ERROR: Exception while getting cpu frequency!
15/02/21 (17:56:21) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.62/libexec/lib/python3.9/site-packages/bpytop.py", line 3034, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.62/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.62/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
26/02/21 (18:43:54) | ERROR: Exception while getting cpu frequency!
26/02/21 (18:43:54) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
02/03/21 (12:31:11) | ERROR: Exception while getting cpu frequency!
02/03/21 (12:31:11) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
02/03/21 (12:36:42) | ERROR: Exception while getting cpu frequency!
02/03/21 (12:36:42) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
04/03/21 (15:36:02) | ERROR: Exception while getting cpu frequency!
04/03/21 (15:36:02) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
08/03/21 (22:02:58) | ERROR: Exception while getting cpu frequency!
08/03/21 (22:02:58) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
12/03/21 (18:07:54) | ERROR: Exception while getting cpu frequency!
12/03/21 (18:07:54) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/bpytop.py", line 3046, in _collect
    if hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
